# Generated by Django 5.1.1 on 2024-09-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=50)),
                ('date_applied', models.DateField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejection', 'Rejection')], default='applied', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
