# Generated by Django 5.1.1 on 2024-09-14 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_skill_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='companyName',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='date_applied',
            new_name='date',
        ),
    ]
