# Generated by Django 5.1.1 on 2024-09-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='work_experiences',
        ),
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(blank=True, default='ABC', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='contact',
            field=models.CharField(blank=True, default='0', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, default='abc@gmail.com', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='employer',
            field=models.CharField(blank=True, default='University of Alberta', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='firstName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
