# Generated by Django 5.1.1 on 2024-09-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_resume_contact_info_remove_resume_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
